const slide = `
{
  "version": "1.1",
  "general": {
      "type": "compose",
      "subtype": "slide",
      "name": "Slide 1",
      "resolutionId": 3,
      "duration": 10000,
      "templateId": 1,
      "showGrid": false
  },
  "objects": [
  {
      "animations": {
        "start": {
           "type": "fadeIn",
           "startTime": 2,
           "duration": 3,
           "repetition": 2
        },
        "end": {
           "type": "fadeOut",
           "startTime": 2,
           "duration": 4,
           "repetition": 2
        }
      },
      "type": "rect",
      "originX": "left",
      "originY": "top",
      "left": 199.44,
      "top": 129.79,
      "width": 200,
      "height": 100,
      "fill": "#3f51b5",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 41.91,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0,
      "id": 714190
    },
    {
      "type": "rect",
      "animations": {
        "start": {
           "type": "fadeIn",
           "startTime": 2,
           "duration": 1,
           "repetition": 1
        },
        "end": {
           "type": "fadeOut",
           "startTime": 2,
           "duration": 1,
           "repetition": 2
        }
      },
      "originX": "left",
      "originY": "top",
      "left": 327,
      "top": 125,
      "width": 100,
      "height": 100,
      "fill": "#4caf50",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0,
      "id": 593146
    },
    {
      "type": "triangle",
      "originX": "left",
      "originY": "top",
      "left": 101,
      "top": 265,
      "width": 100,
      "height": 100,
      "fill": "#2196f3",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "id": 368563
    },
    {
      "animations": {
        "start": {
           "type": "slideInLeft",
           "startTime": 5,
           "duration": 10,
           "repetition": null
        },
        "end": {
           "type": "slideOutRight",
           "startTime": 1,
           "duration": 10,
           "repetition": null
        }
      },
      "type": "circle",
      "originX": "left",
      "originY": "top",
      "left": 119.25,
      "top": 302,
      "width": 100,
      "height": 100,
      "fill": "#ff5722",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 2.16,
      "scaleY": 2.16,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "radius": 50,
      "startAngle": 0,
      "endAngle": 6.283185307179586,
      "id": 980102,
      "url": "http://google.by"
    }
  ],
  "background": "#ffffff"
}
`;

export default slide;
