const slide = `
{
  "version": "2.2.3",
  "general": {
    "type": "compose",
    "subtype": "slide",
    "name": "Slide with video",
    "resolutionId": 3,
    "duration": 10,
    "templateId": 1,
    "showGrid": false
  },
  "objects": [
    {
      "type": "rect",
      "animations": {
        "start": {
           "type": "fadeIn",
           "startTime": 3,
           "duration": 2,
           "repetition": 1
        },
        "end": null
      },
      "version": "2.2.3",
      "originX": "left",
      "originY": "top",
      "left": 290.6,
      "top": 350,
      "width": 78,
      "height": 78,
      "fill": "blue",
      "stroke": null,
      "strokeWidth": 1,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 2.62,
      "scaleY": 2.62,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": {
        "color": "rgb(0,0,0)",
        "blur": 0,
        "offsetX": 0,
        "offsetY": 0,
        "affectStroke": false
      },
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0,
      "showShadow": true
    },
    {
      "type": "image",
      "version": "2.2.3",
      "originX": "left",
      "originY": "top",
      "left": 85,
      "top": 38,
      "width": 1280,
      "height": 720,
      "fill": "blue",
      "stroke": null,
      "strokeWidth": 0,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 0.04,
      "scaleY": 0.04,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": {
        "color": "rgb(0,0,0)",
        "blur": 0,
        "offsetX": 0,
        "offsetY": 0,
        "affectStroke": false
      },
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "crossOrigin": "",
      "cropX": 0,
      "cropY": 0,
      "showShadow": true,
      "src": "https://images.wallpaperscraft.ru/image/devushka_lico_vzryv_92171_1280x720.jpg",
      "filters": []
    },
    {
      "type": "video",
      "version": "2.2.3",
      "originX": "left",
      "originY": "top",
      "left": 5,
      "top": 1,
      "width": 1280,
      "height": 534,
      "fill": "blue",
      "stroke": null,
      "strokeWidth": 0,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 0.53,
      "scaleY": 0.53,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": {
        "color": "rgb(0,0,0)",
        "blur": 0,
        "offsetX": 0,
        "offsetY": 0,
        "affectStroke": false
      },
      "visible": true,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "crossOrigin": "",
      "cropX": 0,
      "cropY": 0,
      "showShadow": true,
      "src": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      "filters": []
    },
    {
      "type": "group",
      "version": "2.2.3",
      "originX": "left",
      "originY": "top",
      "left": 0,
      "top": 0,
      "width": 800,
      "height": 230,
      "fill": "rgb(0,0,0)",
      "stroke": null,
      "strokeWidth": 0,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeLineJoin": "miter",
      "strokeMiterLimit": 10,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": false,
      "clipTo": null,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "transformMatrix": null,
      "skewX": 0,
      "skewY": 0,
      "id": "#_template",
      "showShadow": true,
      "objects": [
        {
          "type": "line",
          "version": "2.2.3",
          "originX": "left",
          "originY": "top",
          "left": -400,
          "top": 105,
          "width": 800,
          "height": 0,
          "fill": "rgb(0,0,0)",
          "stroke": "#B2BBCA",
          "strokeWidth": 10,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 10,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "clipTo": null,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "transformMatrix": null,
          "skewX": 0,
          "skewY": 0,
          "showShadow": true,
          "x1": -400,
          "x2": 400,
          "y1": 0,
          "y2": 0
        },
        {
          "type": "line",
          "version": "2.2.3",
          "originX": "left",
          "originY": "top",
          "left": -5,
          "top": -115,
          "width": 0,
          "height": 225,
          "fill": "rgb(0,0,0)",
          "stroke": "#B2BBCA",
          "strokeWidth": 10,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeLineJoin": "miter",
          "strokeMiterLimit": 10,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "clipTo": null,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "transformMatrix": null,
          "skewX": 0,
          "skewY": 0,
          "showShadow": true,
          "x1": 0,
          "x2": 0,
          "y1": -112.5,
          "y2": 112.5
        }
      ]
    }
  ],
  "background": "#ffffff"
}
`;

export default slide;
